spring:
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/solution-server?characterEncoding=utf8&useSSL=true
    username: root
    password: mytest
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 0
    password: aline
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0 
  output:
    ansi:
      enabled: DETECT
        
shiro:
  session:
    keyPrefix: "shiro_redis_session:"
    validtime: 18000
    
userdao:
  sql:
    getUserByName: "select t.f_username as username, t.f_email as email, t.f_password as password from f_user t where t.f_username = ? or t.f_email = ? "
    getUserByEmail: "select t.f_verified as verify from f_email t where t.f_email = ?"
    