spring:
  redis:
    host: localhost
    port: 6379
    timeout: 0
    password: aline
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0 

  data:
    mongodb:
      uri: mongodb://192.168.1.13:27017/cde-account-service

authc:
  shiro:
    session:
      keyPrefix: "io.cde.auth.session.id:"
      validtime: 180
  simpleCookie:
    name: "io.cde.auth.session.id"
    HttpOnly: true
    MaxAge: -1
  rememberMeCookie:
    name: "io.cde.auth.rememberme.id"
    HttpOnly: true
    MaxAge: 100

#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://discovery-server-1:8761/eureka/,http://discovery-server-2:8762/eureka/
#
#---
#spring:
#  profiles: primary
#server:
#  port: 8081
#eureka:
#  instance:
#    hostname: registration-service-1
#
#---
#spring:
#  profiles: secondary
#server:
#  port: 8082
#eureka:
#  instance:
#    hostname: registration-service-2
